:HEADER:
#+TITLE: General Self-Consistent Field Methods
#+AUTHOR: Vijay Gopal Chilkuri
#+EMAIL: vijay.gopal.c@gmail.com
#+DATA: <2023-05-14 dim.>
#+LaTeX_Header: \documentclass{article}
#+LaTeX_Header: \usepackage{amsmath,amssymb}
#+LaTeX_Header: \newcommand*\Laplace{\mathop{}\!\mathbin\bigtriangleup}
:END:


* Introduction

The Schrodinger equation is a certain class of Boundary Value Problem (BVP).
Solution of the Schrodinger equation results in the eigenvalues($\lambda$) and
eigenvectors ($\psi$) of the Hamiltonian.

\[
\mathcal{L}\psi(x) = \lambda\psi(x)
\]

These type of equations where $\mathcal{L}$ is a second order differential
operator and self-adjoint (i.e. hermitian) is called a Sturm-Liouville problem (SLP).
Sturm-Liouville problems are general eigenvalues problems of the form

#+Label: Eq1
\[
-\frac{d}{dt}\left ( p(t) \frac{d y(t)}{dt} \right ) + q(t)y(t) = \lambda g(t)y(t)
\]

posed on an interval $-\infty \le a \le b \le \infty$ which may be finite or infinite. Such
problem's arise in various fields of physics and chemistry and there exist
robust and well studied numerical and analytical methods for their resolution.

In the present manuscript, we shall document numerical methods for the solution
of various types of Hamiltonians and analyze their spectra and wavefunctions.

* Hydrogen atom

We begin with the most simplest SLP which is the solution
of the Hamiltonian for the hydrogen atom Eq:[[Eq2]]

#+Label: Eq2
\[
\hat{H}\psi(\mathbf{x}) = \left [ -\Laplace + V \right ]\psi(\mathbf{x})
\]

This is the SLP(Eq:[[Eq1]]) with $p(t)=g(t)=1$, and $q(t)=V$, the potential acting
on the particle. The Eq:[[Eq2]] is in cartesian coordinates $\mathbf{x}$ and
can be transformed to spherical coordinates via a coordinate transformation.

#+Label: Eq3
\begin{equation}
\begin{align*}
x_1 &= r\sin{\theta}\cos{\phi},\\
x_2 &= r\sin{\theta}\sin{\phi},\\
x_3 &= r\cos{\theta}
\end{align*}
\end{equation}

In spherical coordinates, the operator $\hat{H}$ is transformed to

#+Label: Eq4
\begin{equation}
\begin{align*}
\hat{H} &= -\frac{1}{r^2}\frac{\partial}{\partial r} \left( r^2 \frac{\partial}{\partial r} \right) \\
&  -\frac{1}{r^2}\frac{1}{\sin{\theta}}\frac{\partial}{\partial\theta} \left(\sin{\theta}\frac{\partial}{\partial\theta} \right)\\
&  -\frac{1}{r^2}\frac{1}{\sin{\theta}^2}\frac{\partial^2}{\partial\phi^2} + V
\end{align*}
\end{equation}

We can then separate the wavefunction to three independent variables
$\psi(\mathbf{x})=R(r)\Theta(\theta)\Phi(\phi)$ to obtain three separate SLPs

#+Label: Eq5
\begin{equation}
\begin{align*}
\left (
-\frac{1}{r^2}\frac{\partial}{\partial r} \left( r^2 \frac{\partial}{\partial r} \right)
+ \frac{l(l+1)}{r^2} + V(r)
 \right)R(r) &= \lambda R(r)\\
\frac{1}{\sin{\theta}}\left (
-\frac{\partial}{\partial \theta} \left( \sin{\theta} \frac{\partial}{\partial \theta} \right)
+ \frac{m^2}{\sin{\theta}}
 \right)\Theta(\theta) &= l(l+1) \Theta(\theta)\\
-\frac{\partial^2}{\partial \phi^2}\Phi(\phi) &= m^2 \Phi(\phi)\\
\end{align*}
\end{equation}

With only $r$ being the dependent variable i.e. the first equation.
Here we can do a further transformation of the dependent variable
$u(r) = r R(r)$ which gives the SLP

#+Label: Eq5
\begin{equation}
\begin{align*}
-\frac{\partial^2 u(r)}{\partial r^2}
+ q(r) u(r) &= \lambda u(r) \\
q(r) &= \frac{l(l+1)}{r^2} + V(r)\\
p(r) &= g(r) = 1
\end{align*}
\end{equation}
