name: Python Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo PYTHONPATH=/home/runner/work/gscf/gscf:$PYTHONPATH)" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pip install .
        python -m pytest --import-mode=append src/
    
    - name: install extra repository
      run: sudo add-apt-repository ppa:kelleyk/emacs
    
    - name: refresh apt
      run: sudo apt-get update
    
    - name: install dependencies
      run: sudo apt-get install emacs
    
    - name: install htmlize
      run: git clone https://github.com/hniksic/emacs-htmlize && cp emacs-htmlize/htmlize.el docs/
    
    - name: make
      run: cd docs ; ./create.sh ../gscf.org ; cd ..
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

