name: Python Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo PYTHONPATH=/home/runner/work/gscf/gscf:$PYTHONPATH)" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pip install .
        python -m pytest --import-mode=append src/
